clinic/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('section.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

section/models.py
from multiselectfield import MultiSelectField
from django.db import models
from django.contrib.auth.models import AbstractUser

class Group(models.Model):
    name = models.CharField(verbose_name='نام گروه', max_length=100)

    class Meta:
        verbose_name = 'گروه'
        verbose_name_plural = 'گروه ها'

    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='custom_user_group', verbose_name='گروه', null=True, blank=True)
    is_manager = models.BooleanField(verbose_name='دسترسی مسئول', default=True)

    class Meta:
        verbose_name = 'اکانت'
        verbose_name_plural = 'اکانت‌ ها'

    def __str__(self):
        return self.username

class Excel(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='excel_group', verbose_name='گروه')
    file = models.FileField(verbose_name='فایل اکسل', upload_to='excels/', default='')

    class Meta:
        verbose_name = 'اکسل'
        verbose_name_plural = 'اکسل ها'
    
    def save(self, *args, **kwargs):
        if hasattr(self, '_user'):
            self.group = self._user.group
        super().save(*args, **kwargs)

class Expertise(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='expertise_group', verbose_name='گروه')
    name = models.CharField(verbose_name='نام تخصص', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'تخصص'
        verbose_name_plural = 'تخصص ها'
    
    def save(self, *args, **kwargs):
        if hasattr(self, '_user'):
            self.group = self._user.group
        super().save(*args, **kwargs)

class Section(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='section_group', verbose_name='گروه')
    name = models.CharField(verbose_name='نام بخش', max_length=100)
    sheet = models.CharField(verbose_name='برگ بخش', max_length=100, null=True, blank=True)
    expertises = models.ManyToManyField(Expertise, related_name='section_expertises', verbose_name='تخصص ها', blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'بخش'
        verbose_name_plural = 'بخش ها'
    
    def save(self, *args, **kwargs):
        if hasattr(self, '_user'):
            self.group = self._user.group
        super().save(*args, **kwargs)

class Room(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='room_group', verbose_name='گروه')
    name = models.CharField(verbose_name='نام اتاق عمل', max_length=100)
    sheet = models.CharField(verbose_name='برگ اتاق عمل', max_length=100, null=True, blank=True)
    expertises = models.ManyToManyField(Expertise, related_name='room_expertises', verbose_name='تخصص ها', blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'اتاق عمل'
        verbose_name_plural = 'اتاق های عمل'
    
    def save(self, *args, **kwargs):
        if hasattr(self, '_user'):
            self.group = self._user.group
        super().save(*args, **kwargs)

class Doctor(models.Model):
    grade_choices = [
        ('1', 'عمومی'),
        ('2', 'متخصص'),
        ('3', 'فوق تخصص'),
    ]

    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='doctor_group', verbose_name='گروه')
    full_name = models.CharField(verbose_name='نام و نام خانوادگی', max_length=100)
    sections = models.ManyToManyField(Section, related_name='doctor_sections', verbose_name='بخش ها', blank=True)
    rooms = models.ManyToManyField(Room, related_name='doctor_rooms', verbose_name='اتاق های عمل', blank=True)
    expertises = models.ManyToManyField(Expertise, related_name='doctor_expertises', verbose_name='تخصص ها', blank=True)
    grade = models.CharField(verbose_name='درجه', max_length=1, choices=grade_choices, null=True, blank=True)
    personnel_code = models.CharField(verbose_name='کد پرسنلی', max_length=100, null=True, blank=True)

    def __str__(self):
        return self.full_name
    
    class Meta:
        verbose_name = 'پزشک'
        verbose_name_plural = 'پزشکان'
    
    def save(self, *args, **kwargs):
        if hasattr(self, '_user'):
            self.group = self._user.group
        super().save(*args, **kwargs)

class Patient(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='patient_group', verbose_name='گروه')
    full_name = models.CharField(verbose_name='نام و نام خانوادگی', max_length=500)
    sections = models.ManyToManyField(Section, related_name='patient_sections', verbose_name='بخش ها', blank=True)
    rooms = models.ManyToManyField(Room, related_name='patient_rooms', verbose_name='اتاق های عمل', blank=True)

    def __str__(self):
        return f'بیمار با نام {self.full_name}'
    
    class Meta:
        verbose_name = 'بیمار'
        verbose_name_plural = 'بیماران'
    
    def save(self, *args, **kwargs):
        if hasattr(self, '_user'):
            self.group = self._user.group
        super().save(*args, **kwargs)

class SectionCase(models.Model):
    defect_sheet_choices = [
        ('1', 'برگ پذیرش خلاصه ترخیص'),
        ('2', 'برگ خلاصه پرونده'),
        ('3', 'برگ شرح حال'),
        ('4', 'برگ سیربیماری'),
        ('5', 'برگ مشاوره'),
        ('6', 'برگ مراقبت قبل از عمل'),
        ('7', 'برگ بیهوشی'),
        ('8', 'برگ شرح عمل'),
        ('9', 'برگ مراقبت بعد از عمل'),
        ('10', 'دستورات پزشک'),
        ('11', 'گزارش پرستار'),
        ('12', 'نمودار علائم حیاتی'),
        ('13', 'رضایت آگاهانه'),
        ('14', 'صورتحساب'),
        ('15', 'چک لیست'),
    ]

    defect_type_choices = [
        ('1', 'عدم درج مهر پزشک'),
        ('2', 'مهر مشاوره'),
        ('3', 'مهر tellorder'),
        ('4', 'فقدان برگ'),
        ('5', 'عدم تکمیل گزارش'),
        ('6', 'خط خوردگی'),
        ('7', 'عدم تکمیل سربرگ'),
        ('8', 'عدم تشخیص نویسی'),
        ('9', 'عدم اخذ رضایت'),
        ('10', 'عدم اثر انگشت و امضا'),
        ('11', 'عدم ثبت دقیق آدرس و تلفن بیمار'),
    ]

    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='section_case_group', verbose_name='گروه')
    insurance = models.CharField(verbose_name='بیمه', max_length=100, null=True, blank=True)
    discharge_date = models.CharField(verbose_name='تاریخ ترخیص', max_length=10, null=True, blank=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, related_name='section_case', verbose_name='بخش')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='doctor_case', verbose_name='پزشک')
    admission_date = models.CharField(verbose_name='تاریخ پذیرش', max_length=10)
    number = models.CharField(verbose_name='شماره پرونده', max_length=50)
    representative_doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='r_doctor_case', verbose_name='پزشک معرف')
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_case', verbose_name='بیمار')
    delivery_date = models.CharField(verbose_name='تاریخ تحویل', max_length=10, null=True, blank=True)
    defect_sheet = models.CharField(verbose_name='برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type = MultiSelectField(verbose_name='نوع نقص', choices=defect_type_choices, null=True, blank=True)
    defect_sheet2 = models.CharField(verbose_name='2 برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type2 = MultiSelectField(verbose_name='2 نوع نقص', choices=defect_type_choices, null=True, blank=True)
    defect_sheet3 = models.CharField(verbose_name='3 برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type3 = MultiSelectField(verbose_name='3 نوع نقص', choices=defect_type_choices, null=True, blank=True)
    defect_sheet4 = models.CharField(verbose_name='4 برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type4 = MultiSelectField(verbose_name='4 نوع نقص', choices=defect_type_choices, null=True, blank=True)
    defect_sheet5 = models.CharField(verbose_name='5 برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type5 = MultiSelectField(verbose_name='5 نوع نقص', choices=defect_type_choices, null=True, blank=True)
    defect_sheet6 = models.CharField(verbose_name='6 برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type6 = MultiSelectField(verbose_name='6 نوع نقص', choices=defect_type_choices, null=True, blank=True)
    defect_sheet7 = models.CharField(verbose_name='7 برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type7 = MultiSelectField(verbose_name='7 نوع نقص', choices=defect_type_choices, null=True, blank=True)
    defect_sheet8 = models.CharField(verbose_name='8 برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type8 = MultiSelectField(verbose_name='8 نوع نقص', choices=defect_type_choices, null=True, blank=True)
    defect_sheet9 = models.CharField(verbose_name='9 برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type9 = MultiSelectField(verbose_name='9 نوع نقص', choices=defect_type_choices, null=True, blank=True)
    defect_sheet10 = models.CharField(verbose_name='10 برگ نقص', max_length=2, choices=defect_sheet_choices, null=True, blank=True)
    defect_type10 = MultiSelectField(verbose_name='10 نوع نقص', choices=defect_type_choices, null=True, blank=True)

    def __str__(self):
        return self.number
    
    class Meta:
        verbose_name = 'پرونده بخش'
        verbose_name_plural = 'پرونده های بخش'
    
    def save(self, *args, **kwargs):
        if hasattr(self, '_user'):
            self.group = self._user.group
        super().save(*args, **kwargs)

class RoomCase(models.Model):

templates/dc_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
جزئیات پرونده DC: {{ dc.number }}
{% endblock %}

{% block page1 %}
پرونده های DC
{% endblock %}

{% block page2 %}
جزئیات پرونده DC: {{ dc.number }}
{% endblock %}

{% block contain %}
<div class="row">
    <div class="my-grid">
        <div>
            <label>شماره پرونده</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.number }}" disabled>
            </div>
        </div>
        <div>
            <label>پزشک</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.doctor.full_name }}" disabled>
            </div>
        </div>
        <div>
            <label>علت فوت</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.cause_of_death }}" disabled>
            </div>
        </div>
        <div>
            <label>بخش محل فوت</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.location_of_death }}" disabled>
            </div>
        </div>
        <div>
            <label>بخش بستری</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.hospitalization_section.name }}" disabled>
            </div>
        </div>
        <div>
            <label>تاریخ فوت</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.death_date }}" disabled>
            </div>
        </div>
        <div>
            <label>تاریخ پذیرش</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.admission_date }}" disabled>
            </div>
        </div>
        <div>
            <label>سن بیمار</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.age }}" disabled>
            </div>
        </div>
        <div>
            <label>جنسیت بیمار</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.get_gender_display }}" disabled>
            </div>
        </div>
        <div>
            <label>بیمار</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.patient.full_name }}" disabled>
            </div>
        </div>
        <div>
            <label>تاریخ تحویل</label>
            <div class="mb-3">
                <input type="text" class="form-control" value="{{ dc.delivery_date }}" disabled>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/doctor_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
پزشکان
{% endblock %}

{% block page1 %}
پزشکان
{% endblock %}

{% block page2 %}
پزشکان
{% endblock %}

{% block contain %}
<div class="row">
    <div class="col-12">
        <h5>جستجو پزشکان <span style="font-size: small; color: #f97316;">پر کردن تمامی موارد الزامی نیست</span></h5>
        <form method="get" class="my-form">
            <input title="کد پرسنلی" type="number" name="personnel_code" class="form-control w-40" placeholder="کد پرسنلی" style="width: 100% !important;"
                value="{{ request.GET.personnel_code }}">
            <input title="نام پزشک" type="text" name="q" class="form-control w-40" placeholder="نام پزشک" style="width: 100% !important;"
                value="{{ request.GET.q }}">
            <select name="expertise" multiple class="form-control" title="تخصص ها">
                {% for expertise in expertise_list %}
                    <option value="{{ expertise.id }}"
                        {% if expertise.id in selected_expertises %}selected{% endif %}>
                        {{ expertise.name }}
                    </option>
                {% endfor %}
            </select>

            <button class="my-btn" style="background-color: #fff; border: 1px solid #f97316; border-radius: 0.5rem; color: #f97316; padding: 8px 32px; font-size: 0.75rem; font-weight: 700;">جستجو</button>
        </form>
    </div>
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0" style="display: flex; justify-content: space-between;">
                <h6>لیست پزشکان <span><a href="{% url 'analyze_doctor' %}" style="font-size: small; color: #f97316;">مقایسه و آنالیز</a></span></h6>
                <button
                    style="background-color: #fff; border: 1px solid #f97316; border-radius: 0.5rem; color: #f97316; padding: 8px 32px; font-size: 0.75rem; font-weight: 700;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                        class="bi bi-plus" viewBox="0 0 16 16">
                        <path
                            d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
                    </svg>
                    <a href="{% url 'doctor_create' %}" style="color: #f97316;">افزودن پزشک</a>
                </button>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
                <div class="table-responsive p-0">
                    <table class="table align-items-center mb-0">
                        <thead>
                            <tr>
                                <th
                                    class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    شناسه</th>
                                <th
                                    class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    نام پزشک</th>
                                <th
                                    class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    کد پرسنلی</th>
                                <th
                                    class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    درجه</th>
                                <th
                                    class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    تخصص ها</th>
                                <th
                                    class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    اکشن</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if doctors %}
                            {% for doctor in doctors %}
                            <tr>
                                <td class="align-middle text-center">
                                    <span class="text-secondary text-xs font-weight-bold">{{ doctor.id }}</span>
                                </td>
                                <td class="align-middle text-center">
                                    <span class="text-secondary text-xs font-weight-bold">{{ doctor.full_name }}</span>
                                </td>
                                <td class="align-middle text-center">
                                    {% if doctor.personnel_code %}
                                    <span class="text-secondary text-xs font-weight-bold">{{ doctor.personnel_code }}</span>
                                    {% else %}
                                    <span class="text-secondary text-xs font-weight-bold">----</span>
                                    {% endif %}
                                </td>
                                <td class="align-middle text-center">
                                    {% if doctor.get_grade_display %}
                                    <span class="text-secondary text-xs font-weight-bold">{{ doctor.get_grade_display }}</span>
                                    {% else %}
                                    <span class="text-secondary text-xs font-weight-bold">----</span>
                                    {% endif %}
                                </td>
                                <td class="align-middle text-center">
                                    {% for expertise in doctor.expertises.all %}
                                    <span class="text-secondary text-xs font-weight-bold">{{ expertise.name }},</span>
                                    {% endfor %}
                                </td>
                                <td class="align-middle text-center">
                                    <a href="{% url 'doctor_detail' doctor.id %}" title="جزئیات" style="padding: 0 4px;">
                                        <span class="text-secondary text-xs font-weight-bold">
                                            <svg style="color: #f97316; cursor: pointer;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                                            </svg>
                                        </span>
                                    </a>
                                    <a href="{% url 'doctor_update' doctor.id %}" title="ویرایش" style="padding: 0 4px;">
                                        <span class="text-secondary text-xs font-weight-bold">
                                            <svg style="color: #16C47F; cursor: pointer;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                                            </svg>
                                        </span>
                                    </a>
                                    <a href="{% url 'doctor_delete' doctor.id %}" title="حذف" style="padding: 0 4px;">
                                        <span class="text-secondary text-xs font-weight-bold">
                                            <svg style="color: #C5172E; cursor: pointer;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                                <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                                            </svg>
                                        </span>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="6" class="align-middle text-center">
                                    <span class="text-secondary text-xs font-weight-bold">موردی یافت نشد</span>
                                </td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="page">
            {% if page_obj.has_previous %}
            <a href="{% url 'doctor_list' %}?page={{ page_obj.previous_page_number }}">
                <div class="ago">
                    <p>قبلی</p>
                </div>
            </a>
            {% if page_obj.number > 3 %}
            <a href="{% url 'doctor_list' %}?page=1" class="number">1</a>
                {% if page_obj.number > 4 %}
                <span class="number">...</span>
                {% endif %}
            {% endif %}
            {% endif %}
            
            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <a href="{% url 'doctor_list' %}?page={{ num }}" class="number">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} 
            <a href="{% url 'doctor_list' %}?page={{ num }}" class="number">{{ num }}</a>
            {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
            {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
            <span class="number">...</span>
            <a href="{% url 'doctor_list' %}?page={{ page_obj.paginator.num_pages }}" class="number">{{ page_obj.paginator.num_pages }}</a>
            {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %} 
            <a href="{% url 'doctor_list' %}?page={{ page_obj.paginator.num_pages }}" class="number">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
            
            <a href="{% url 'doctor_list' %}?page={{ page_obj.next_page_number }}">
                <div class="next">
                    <p>بعدی</p>
                </div>
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/expertise_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
حذف تخصص: {{ expertise.name }}
{% endblock %}

{% block page1 %}
تخصص ها
{% endblock %}

{% block page2 %}
حذف تخصص: {{ expertise.name }}
{% endblock %}

{% block contain %}
<div class="row" style="text-align: center; padding-top: 50px;">
    <h5 style="color: #f97316;">
        آیا از حذف تخصص: {{ expertise.name }} اطمینان دارید؟
    </h5>

    <form method="post"> {% csrf_token %}
        <br>
        <br>
        <button class="btn btn-netcopy_net" style="margin-left: 10px; color: red;">تایید و حذف</button>
        <a href="{% url 'expertise_list' %}">بیخیال!</a>
    </form>
</div>
{% endblock %}

templates/expertise_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
فرم ایجاد تخصص
{% endblock %}

{% block page1 %}
تخصص ها
{% endblock %}

{% block page2 %}
فرم ایجاد تخصص
{% endblock %}

{% block contain %}
<div class="row">
    <form method="post">
        {% csrf_token %}
        <h3 style="margin-bottom: 20px;">فرم ایجاد تخصص</h3>

        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="error">{{ error }}</p>
        {% endfor %}
        {% endif %}

        <div class="my-grid">
            <div>
                <label>{{ form.name.label }}</label>
                <div class="mb-3">
                    <input type="text" name="name" class="form-control" value="{{ form.name.value|default:'' }}">
                </div>
                {% if form.name.errors %}
                {% for error in form.name.errors %}
                <p class="error">{{ error }}</p>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="text-center">
            <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">ثبت جزئیات تخصص</button>
        </div>
    </form>
</div>
{% endblock %}

templates/room_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
حذف اتاق عمل: {{ room.name }}
{% endblock %}

{% block page1 %}
اتاق های عمل
{% endblock %}

{% block page2 %}
حذف اتاق عمل: {{ room.name }}
{% endblock %}

{% block contain %}
<div class="row" style="text-align: center; padding-top: 50px;">
    <h5 style="color: #f97316;">
        آیا از حذف اتاق عمل: {{ room.name }} اطمینان دارید؟
    </h5>
    <h6 style="color: red;">
        پرونده های این اتاق عمل نیز حذف خواهد شد
    </h6>

    <form method="post"> {% csrf_token %}
        <br>
        <br>
        <button class="btn btn-netcopy_net" style="margin-left: 10px; color: red;">تایید و حذف</button>
        <a href="{% url 'room_list' %}">بیخیال!</a>
    </form>
</div>
{% endblock %}

templates/section_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
حذف بخش: {{ section.name }}
{% endblock %}

{% block page1 %}
بخش ها
{% endblock %}

{% block page2 %}
حذف بخش: {{ section.name }}
{% endblock %}

{% block contain %}
<div class="row" style="text-align: center; padding-top: 50px;">
    <h5 style="color: #f97316;">
        آیا از حذف بخش: {{ section.name }} اطمینان دارید؟
    </h5>
    <h6 style="color: red;">
        پرونده های این بخش نیز حذف خواهد شد
    </h6>

    <form method="post"> {% csrf_token %}
        <br>
        <br>
        <button class="btn btn-netcopy_net" style="margin-left: 10px; color: red;">تایید و حذف</button>
        <a href="{% url 'section_list' %}">بیخیال!</a>
    </form>
</div>
{% endblock %}